// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsUPT1osKFKJlRJInEEYxwOowuklRWnyc',
    appId: '1:245041128693:android:5ec192e6e184d82c7551bc',
    messagingSenderId: '245041128693',
    projectId: 'footlog-dca3c',
    storageBucket: 'footlog-dca3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_8dllGWt8i7s_uPSba5j2TrIm0iAsTCE',
    appId: '1:245041128693:ios:cc805281560b0d127551bc',
    messagingSenderId: '245041128693',
    projectId: 'footlog-dca3c',
    storageBucket: 'footlog-dca3c.firebasestorage.app',
    androidClientId: '245041128693-aec85u57s0muol59f2t8c33ge0qipjk3.apps.googleusercontent.com',
    iosClientId: '245041128693-qrire5sit9e7r8264ga3i1t6in8lulp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.footlog',
  );

}